### PR TITLE
Added Danish translation

### PR DESCRIPTION
**Pull request by NicoDK6400**
Just another one for the translations

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Review by FjamZoo — CHANGES_REQUESTED** [review]
entered_vehicle should be altered to this ["entered_vehicle"] = "Steg ind i bilen",

since "steg i bilen" dosn't make sense

**Comment by NicoDK6400** [comment]
> 

Changed! Thanks you!

**Review by FjamZoo — APPROVED** [review]
Danish translations are now good to be merged

**Review by jay-fivem — APPROVED** [review]
Approved

**Comment by FjamZoo** [comment]
Another PR has been pulled regarding Danish translation as they used more native danish other than keywords such as "Spawn" etc. as thats not really considered danish even though 99% of danish people would understand it.

Tusind tak for din PR alligevel 👍

**Pull request closed without merging**
