### PR TITLE
STAFFCHAT fix

### PR DESCRIPTION
**Pull request by ArtysV**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by Brusein** [comment]
I did test this today and it worked for me.

**Comment by GhzGarage** [comment]
Please update using this: https://docs.fivem.net/docs/scripting-manual/migrating-from-deprecated/chat-messages/

**Comment by Andyauk** [comment]
I'm not sure why close this, as it does work, where the one in the main code don't.

**Comment by GhzGarage** [comment]
I already updated it

**Comment by Andyauk** [comment]
> I already updated it

Ah ok buddy, sorry.

**Pull request closed without merging**
