### PR TITLE
fix for maxmods for cars

### LINKED ISSUE #160: [SUGGESTION] Maxmods works on spawned vehicles.
Maxmods only work on spawned vehicles if you have been in benny's

Love to see if you can use it directly on a spanwed vehicle

### PR DESCRIPTION
**Pull request by xanten11**
you can now use /maxmods on any car anyplace and it will work not need to open up bennys

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here
this should fix #160 
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by xanten11** [comment]
this should solve issue [SUGGESTION] Maxmods works on spawned vehicles. #160 
https://github.com/qbcore-framework/qb-adminmenu/issues/160

**Comment by xanten11** [comment]
@GhzGarage feel free to review the patch

**Comment by GhzGarage** [comment]
@Sylvernl88 test?

**Comment by xanten11** [comment]
i have tested my self with 10 cars i have known it was not working with and it works every time now but 100% test it out

**Comment by xanten11** [comment]
@GhzGarage not sure is @sylvenl88 is active in git atm  but if anyone else wants to test this and review it feel free its here

**Comment by Sylvernl88** [comment]
> @GhzGarage not sure if @sylvenl88 is active in git atm but if anyone else wants to test this and review it feel free its here

It works thx

**Comment by xanten11** [comment]
> > @GhzGarage not sure if @sylvenl88 is active in git atm but if anyone else wants to test this and review it feel free its here
> 
> It works thx

thanks for testing and leting me know the issue to fix !

**Pull request merged**
