### PR TITLE
We would like a more improved noclip system.

### PR DESCRIPTION
**Pull request by darknight2590**
This code is better than the current one, and it has better control, especially in the subject of flight, and better control and realistically without going down to the ground as you go further.
The old one is very bad

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by darknight2590** [comment]
More freedom to move around in vehicles
Not falling underground
Flying in a straight line, not diagonally
More features and more problem solving than the old version

**Comment by BerkieBb** [comment]
Could you showcase this noclip with a video?

**Comment by GhzGarage** [comment]
Conflicts

**Comment by Molicheu** [comment]
https://github.com/d3rp-jsx/noclip-pro

**Pull request closed without merging**
