### PR TITLE
small update

### PR DESCRIPTION
**Pull request by ChatDisabled**
**Describe Pull request**
small update

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
YES
- Does your code fit the style guidelines? [yes/no]
I am the style guideline
- Does your PR fit the contribution guidelines? [yes/no]
YES

### CODE REVIEW

**Comment by ChatDisabled** [comment]
@ihyajb I stole [your pr](https://github.com/qbcore-framework/qb-adminmenu/pull/107)

**Comment by ihyajb** [comment]
:(

**Comment by ihyajb** [comment]
All good ill close mine. Also why put the sounds in its own qb-menu? why not do it like how spawning vehicles is and just but it into the actual menu?

**Comment by ChatDisabled** [comment]
> All good ill close mine. Also why put the sounds in its own qb-menu? why not do it like how spawning vehicles is and just but it into the actual menu?

qb-menu seemed to be the better fit for selecting which sound you want. There were more things planned as well that deemed to be better in qb-menu. Conversion is of course not hard at all.

**Comment by ihyajb** [comment]
yeah i get what your saying just seemed weird to me wanted to see your reasoning behind it. All in all good PR, I have one suggestion however, maybe an option just like sounds. But for routing buckets 🤷🏼‍♂️

**Comment by ChatDisabled** [comment]
That's the thing, more was planned but it should be easier now for other people as well to PR to keep things more organized. And I will be doing more PRs in the future

**Comment by SharkyFP** [comment]
Hey I found a bug that I can't change the reason for player ban. Any inputs on that ?

**Comment by ChatDisabled** [comment]
@SharkyFP I can tho just tested. Do you have qb-menu installed?

**Comment by SharkyFP** [comment]
> @SharkyFP I can tho just tested. Do you have qb-menu installed?

Yeah I do, but also I managed to fix it I had a type error when changing something. All good now.

**Comment by ItsANoBrainer** [comment]
Changelog?

**Comment by ChatDisabled** [comment]
@ItsANoBrainer read the fucking code.

Changelog: It works

**Comment by BerkieBb** [comment]
> @ItsANoBrainer read the fucking code.
> 
> Changelog: It works

You read it and let me know

**Comment by ChatDisabled** [comment]
> You read it and let me know

I read it, it states that it has a better and more readible code now with additional features

**Comment by BerkieBb** [comment]
> > You read it and let me know
> 
> I read it, it states that it has a better and more readible code now with additional features

Now tell me all the features

**Comment by ChatDisabled** [comment]
> > > You read it and let me know
> > 
> > 
> > I read it, it states that it has a better and more readible code now with additional features
> 
> Now tell me all the features

seems to be the ability to play audio on players, better logic / converted to server logic for existing features and implementing some commands inside the menu itself

**Comment by JonasDev99** [comment]
admincar adds the car 4 times to the db and unlimited ammo doesn't work when you have 0 bullets initially. 
Honestly, I don't think anyone's gonna look at this code because its a huge update in one commit and no information at all about what's been implemented. You should break this code down in multiple commits or even in multiple PRs, maybe then someone's gonna look at it.

**Comment by ChatDisabled** [comment]
> admincar adds the car 4 times to the db
Good thing I didn't change anything at all with this feature and that that is standard or wrong use case.
> unlimited ammo doesn't work when you have 0 bullets initially
Will be fixed in future PR
> I don't think anyone's gonna look at this code
Good thing that multiple people did, there is literally nothing complicated at all. What I renamed a few things so it looks like a big update that's all? Smh I really have to point out everything in here

1. Replaced the export under main.lua since that's main.lua and makes more sense?
2. Added the CB `qb-adminmenu:callback:haspermission` that's gonna be removed anyways in a future update since I want something more secure to deal with this if possible.
3. Renamed every stupid name and gave proper naming to vars, events, naming, etc. This will give everyone the ability to properly 
4. Restructered the player list when clicking on a player since "more features planned soon" otherwise the menu would be too big.
5. Added a function to play sounds directly on players using the interact-sound resource that comes with QBCore. Could easily be changed to something else.
6. Better logic behaviour for existing features
7. Stole AJ's PR about delete lazer
8. Better server sided logic in general

Can I get a rest now? Have to spent more time detailing this shit then coding

**Comment by JonasDev99** [comment]
> Good thing I didn't change anything at all with this feature and that that is standard or wrong use case.

You're right, I think it know what it was and that was my fault.

> Can I get a rest now? Have to spent more time detailing this shit then coding

It would just make it a bit easier for the people who have to test/review/approve your PR and the PR would probably be approved much faster and not sit there for 2+ weeks.

I am just trying to help you fix your code and getting this PR approved, I am not trying to "attack" you or something like that.

**Comment by ChatDisabled** [comment]
PR is sitting here for 2 weeks because they were still deciding on wether to use easyAdmin or not. Imagine using something that looks that ugly (❁´◡`❁)

**Comment by vosscat** [comment]
set player permission from menu gives error after updated latest core with new permission.

**Comment by ChatDisabled** [comment]
> set player permission from menu gives error after updated latest core with new permission.

Prob still fully functional with the old permission system if toggled to true

**Comment by BerkieBb** [comment]
> > set player permission from menu gives error after updated latest core with new permission.
> 
> Prob still fully functional with the old permission system if toggled to true

The old one was completely removed, the old-new one aswell, we only use ace permissions now

**Comment by ChatDisabled** [comment]
> The old one was completely removed, the old-new one aswell, we only use ace permissions now

Well I just know someone would be willing to convert it then :)

**Pull request closed without merging**
