### PR TITLE
Adding Weapon spawn list and Max mod car command and menu button 

### PR DESCRIPTION
**Pull request by xanten11**
making this to add Spawning Weapon list to Qb-adminmenu and to add maxmods to a car in menu and with command 

- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?    Yes
- Does your code fit the style guidelines?     Yes
- Does your PR fit the contribution guidelines?       Yes

i have just updated this to match with other PR's that just got added

### CODE REVIEW

**Comment by xanten11** [comment]
@GhzGarage  i had to make a new PR i started my enhancement to the Menu  with the new PR merge and wanted to clean some things up should be good now if you want to take a look again

**Comment by xanten11** [comment]
there all FIXED !!!

**Comment by GhzGarage** [comment]
> @GhzGarage i had to make a new PR i started my enhancement to the Menu with the new PR merge and wanted to clean some things up should be good now if you want to take a look again

Sounds good thank you I will tonight!

**Comment by xanten11** [comment]
> > @GhzGarage i had to make a new PR i started my enhancement to the Menu with the new PR merge and wanted to clean some things up should be good now if you want to take a look again
> 
> Sounds good thank you I will tonight!

sounds good !

**Comment by IdrisDose** [comment]
Should be reverted, I too love callable events to modify vehicles and give weapons.

**Comment by xanten11** [comment]
> Should be reverted, I too love callable events to modify vehicles and give weapons.

I mean you can disable all buttons your self this admin menu is more for help with dev things and also moderation of citys you do not need to use every feature this comes in handy for devs working on cars tuning them for there citys and also testing gun mods and custom gun edits

**Comment by JericoFX** [comment]
i think this need a layer of security first, at least check if the event is fired by qb-core (in the callback event) or from qb-admin and check if the source is actually an admin, just an idea

**Pull request merged**
